#!/usr/bin/env bash
# checking for command line arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# parameters  assignet to variables

path_to_file=$1
ip=$2
username=$3
path_to_SSH_key=$4

#Strict host key checking must be disabled when using scp

scp -o "StrictHostKeyChecking=no" -i "$path_to_SSH_key" "$path_to_file" "$username@$ip:~/"


#if transfer was sucessful
if [ $? -eq 0 ]
then
	echo "File transferred successfully"
else
	echo "File not transferred"
fi
