#!/usr/bin/env bash
# custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for syntax errors
sudo nginx -t

#restart after m,aking changes
sudo service nginx restart
