#!/usr/bin/env bash
#Enable Nginx installation to listen on port 80

#Remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default

#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
service nginx restart
