#!/usr/bin/env bash
#Displays bad luck, good luck and Best School
counter=1
while [ $counter -le 10 ];
do
  if [ $counter -eq 4 ];
then
  echo "bad luck"
elif [ $counter -eq 8 ];
then
  echo "good luck"
else
  echo "Best School"
fi
counter=$((counter + 1))
done
