#!/usr/bin/env bash
#Displays content of the current directory
#In a list format
#Where only part of name after first dash is displayed
list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
