#!/usr/bin/env bash
if [ ! -f /etc/nginx/nginx.conf ]; then
    echo "Error: /etc/nginx/nginx.conf not found."
    exit 1
fi

# Check if the default site configuration file exists
if [ ! -f /etc/nginx/sites-available/default ]; then
    echo "Error: /etc/nginx/sites-available/default not found."
    exit 1
fi

# Update Nginx configuration to run as the nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx for the changes to take effect
service nginx restart

# Display Nginx processes to verify the user and port
ps auxff | grep ngin[x]

# Check if Nginx is listening on port 8080
nc -z localhost 8080 ; echo $?
