#!/usr/bin/env bash
# Stop Nginx if it is already running
service nginx stop

# Update Nginx configuration to run as the nginx user
sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx default site configuration to listen on all active IPs on port 8080
sed -i '/listen/s/80/8080/' /etc/nginx/sites-available/default

# Start Nginx with the updated configuration
service nginx start

# Display the process hierarchy for Nginx
ps auxff | grep "[n]ginx"

# Check if Nginx is listening on port 8080
nc -z 0 8080 ; echo $?
