#!/usr/bin/env bash
# Update Nginx configuration to run as the nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx for the changes to take effect
service nginx restart

# Display Nginx processes to verify the user and port
ps auxff | grep ngin[x]

# Check if Nginx is listening on port 8080
nc -z localhost 8080 ; echo $?
