#!/usr/bin/env bash
service nginx stop
sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen/s/80/8080/' /etc/nginx/sites-available/default
service nginx start
ps auxff | grep "[n]ginx"
nc -z 0 8080
