#!/usr/bin/env bash
#Serve a page with nginx

# /etc/nginx/sites-available/2-app_server-nginx_config

server {
    listen 80 default_server;
    server_name _;

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Additional locations for other routes or apps can be added here.

    location / {
        # Default location, you can adjust this as needed.
        # This could be a different app or static content.
        proxy_pass http://127.0.0.1:5003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
