#!/usr/bin/env bash
#Add a route with query parameters

# /etc/nginx/sites-available/3-app_server-nginx_config

server {
    listen 80 default_server;
    server_name _;

    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://127.0.0.1:5003;  # Assuming your main app is on port 5003
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
